global using System;
global using System.Linq;
global using FluentAssertions;
global using FsCheck;
global using nGGPO.Tests.Utils;
global using nGGPO.Tests.Utils.Assertions;
global using nGGPO.Tests.Utils.Fixtures;
global using nGGPO.Tests.Utils.Network;
global using nGGPO.Tests.Utils.Types;
global using Xunit;
global using Random = System.Random;
