global using System;
global using System.Linq;
global using Bogus;
global using FakeItEasy;
global using FakeItEasy.AutoFakeIt;
global using FluentAssertions;
global using FsCheck;
global using Xunit;
global using GameInput = Backdash.Sync.Input.GameInput<Backdash.Tests.TestUtils.TestInput>;
global using Random = System.Random;
